In [60]:
import pandas as pd
import numpy as np

In [61]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, LabelEncoder,StandardScaler,MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

In [62]:
df=pd.read_csv('Indian_company.csv')

In [63]:
df.sample(5)

,Unnamed: 0,name,rating,reviews,type,headquarter,years_old,employees,service_type
152,152,Muthoot Fincorp,4.1,3100,Conglomerate,Trivandrum/Thiruvananthapuram,137 years old,10k-50k,NBFC
86,86,Tata Projects,4.3,4300,Public,Mumbai,45 years old,5k-10k,Engineering & Construction
11,11,Axis Bank,3.9,22000,Public,Mumbai,31 years old,50k-1 Lakh,Banking
143,143,Optum,4.0,3400,NaN,Prairie,47 years old,10k-50k,Healthcare
145,145,Nagarjuna Construction Company,4.2,3100,Public,Hyderabad/Secunderabad,26 years old,5k-10k,Engineering & Construction

In [64]:
df1=df[['rating','reviews','type']]

In [65]:
df1.sample(5)

    rating  reviews      type
40     4.1     7700   Public
8      3.7    29300   Public
18     4.0    17700       NaN
84     3.6     4400   Public
28     3.5     9600       NaN

In [66]:
df1['type'].fillna(df1['type'].mode()[0],inplace=True)

C:\Users\subas\AppData\Local\Temp\ipykernel_17768\545914235.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['type'].fillna(df1['type'].mode()[0],inplace=True)

In [67]:
df1.sample(5)

     rating  reviews                  type
137     3.9     3400       Indian Unicorn
191     4.1     2400   Forbes Global 2000
121     3.8     3500               Public
50      4.1     6300               Public
119     3.7     3700               Public

In [78]:
column_transform=ColumnTransformer([('trans_rating',StandardScaler(),['rating']),('trans_review',MinMaxScaler(),['reviews']),('trans_type',OneHotEncoder(sparse_output=False),['type'])])

In [79]:
df2=column_transform.fit_transform(df1)

In [80]:
transformed_feature_names = column_transform.named_transformers_['trans_type'].get_feature_names_out(['type'])

In [81]:
new_columns=list(df1.columns.drop('type'))+list(transformed_feature_names)

In [82]:
new_columns

['rating',
 'reviews',
 'type_ Conglomerate ',
 'type_ Forbes Global 2000 ',
 'type_ Fortune India 500 ',
 'type_ Indian Unicorn ',
 'type_ Public ',
 'type_ Startup ']

In [83]:
len(new_columns)

8

In [84]:
df2.shape

(200, 8)

In [85]:
df2

array([[-0.79289938,  1.        ,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 0.0100367 ,  0.61157025,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [-0.39143134,  0.54545455,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.39143134,  0.00275482,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [-0.39143134,  0.00275482,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.21444083,  0.00137741,  0.        , ...,  0.        ,
         1.        ,  0.        ]])

In [86]:
df2=pd.DataFrame(df2,columns=new_columns)

In [87]:
df2

,rating,reviews,type_ Conglomerate,type_ Forbes Global 2000,type_ Fortune India 500,type_ Indian Unicorn,type_ Public,type_ Startup
0,-0.792899,1.000000,0.0,0.0,0.0,0.0,1.0,0.0
1,0.010037,0.611570,0.0,0.0,0.0,0.0,1.0,0.0
2,-0.391431,0.545455,0.0,1.0,0.0,0.0,0.0,0.0
3,-0.792899,0.523416,0.0,0.0,0.0,0.0,1.0,0.0
4,-0.792899,0.443526,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
195,-1.595835,0.004132,0.0,0.0,0.0,0.0,1.0,0.0
196,-0.792899,0.002755,0.0,1.0,0.0,0.0,0.0,0.0
197,-0.391431,0.002755,0.0,0.0,0.0,0.0,1.0,0.0
198,-0.391431,0.002755,0.0,0.0,1.0,0.0,0.0,0.0
199,1.214441,0.001377,0.0,0.0,0.0,0.0,1.0,0.0