In [8]:
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

In [3]:
df=pd.read_csv('titanic_dataset/train.csv')

In [9]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [10]:
df.sample(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
827,828,1,2,"Mallet, Master. Andre",male,1.0,0,2,S.C./PARIS 2079,37.0042,NaN,C
626,627,0,2,"Kirkland, Rev. Charles Leonard",male,57.0,0,0,219533,12.3500,NaN,Q

In [12]:
df.drop(columns=['PassengerId','Name', 'Ticket','Cabin'],inplace=True)

In [13]:
df.sample()

     Survived  Pclass   Sex   Age  SibSp  Parch   Fare Embarked
604         1       1  male  35.0      0      0  26.55        C

In [23]:
# imputation transformer
trf1=ColumnTransformer([('impute_age',SimpleImputer(strategy="median"),[3]),
                       ('impute_Embarked',SimpleImputer(strategy='most_frequent'),[7])],
                      remainder='passthrough')

In [25]:
# encoding and scaling:
trf2=ColumnTransformer([('ohe_sex',OneHotEncoder(sparse=False,handle_unknown='ignore'),[2,7]),
                        ('standard_scaler',StandardScaler(),[3,6])]
                       ,remainder='passthrough')

In [26]:
pipe=Pipeline([('trf1',trf1),
              ('trf2',trf2)])

In [28]:
df1=pd.DataFrame(pipe.fit_transform(df))

C:\Users\subas\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [29]:
df1

,0,1,2,3,4,5,6,7,8,9,...,246,247,248,249,250,251,252,253,254,255
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.827377,-0.473674,22.0,S,male,1
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,-1.566107,-0.473674,38.0,C,female,1
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.827377,-0.473674,26.0,S,female,0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,-1.566107,-0.473674,35.0,S,female,1
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.827377,-0.473674,35.0,S,male,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,-0.369365,-0.473674,27.0,S,male,0
887,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,-1.566107,-0.473674,19.0,S,female,0
888,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.827377,2.008933,28.0,S,female,1
889,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,-1.566107,-0.473674,26.0,C,male,0
890,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.827377,-0.473674,32.0,Q,male,0