In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('Student_Performance.csv')

In [4]:
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [5]:
df.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [7]:
df.drop(columns=['Extracurricular Activities'],inplace=True)

In [8]:
df.head()

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,9,1,91.0
1,4,82,4,2,65.0
2,8,51,7,2,45.0
3,5,52,5,2,36.0
4,7,75,8,5,66.0

In [9]:
df.shape

(10000, 5)

In [10]:
X=df.iloc[:,0:4]
y=df.iloc[:,-1]

In [11]:
X.head()

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced
0,7,99,9,1
1,4,82,4,2
2,8,51,7,2
3,5,52,5,2
4,7,75,8,5

In [12]:
y.head()

0    91.0
1    65.0
2    45.0
3    36.0
4    66.0
Name: Performance Index, dtype: float64

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [16]:
from sklearn.linear_model import LinearRegression

In [19]:
lr=LinearRegression()

In [20]:
lr.fit(X_train,y_train)

LinearRegression()

In [25]:
y_pred=lr.predict(X_test)

In [36]:
y_pred

array([55.00786377, 22.31444624, 47.59404705, ..., 16.48182916,
       63.64243731, 46.23799491])

In [27]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [30]:
MAE=mean_absolute_error(y_test,y_pred)
MSE=mean_squared_error(y_test,y_pred)
RMSE=np.sqrt(mean_squared_error(y_test,y_pred))
R2=r2_score(y_test,y_pred)

In [32]:
print(f'MAE={MAE}\nMSE={MSE}\nRMSE={RMSE}\nR2={R2}')

MAE=1.6296726874197032
MSE=4.182254914593825
RMSE=2.045056213064527
R2=0.9887144552384186

In [34]:
lr.coef_

array([2.85289351, 1.01703572, 0.47331832, 0.19172629])

In [35]:
lr.intercept_

-33.60206732749278