In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
import time

In [2]:
df=pd.read_csv('../Multiple linear regression/Student_Performance.csv')

In [3]:
df.drop(columns=['Extracurricular Activities'],inplace=True)

In [4]:
df.sample(5)

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
8432,9,90,6,9,88.0
2419,7,62,9,0,58.0
5831,7,71,8,6,66.0
8750,5,73,5,3,59.0
5919,5,90,4,8,75.0

In [5]:
df.shape

(10000, 5)

In [6]:
trf=ColumnTransformer([('trf_columns',StandardScaler(),[0,1,2,3])],remainder='passthrough')

In [7]:
df1=pd.DataFrame(trf.fit_transform(df))

In [8]:
df1.sample(4)

             0         1         2         3     4
3751 -0.769703  1.185213  0.866505  0.494105  69.0
4934  0.002742 -1.524926 -0.312895 -1.249754  28.0
3321  0.388965  1.069888 -0.902594  0.842877  77.0
3565 -1.542149 -1.121288  0.276805 -1.598526  24.0

In [9]:
X=df1.iloc[:,0:4]
y=df1.iloc[:,-1]

In [10]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [11]:
lr=LinearRegression()

In [12]:
lr.fit(X_train,y_train)

LinearRegression()

In [13]:
y_pred=lr.predict(X_test)

In [14]:
y_pred

array([55.00786377, 22.31444624, 47.59404705, ..., 16.48182916,
       63.64243731, 46.23799491])

In [15]:
coef=lr.coef_

In [16]:
coef

array([ 7.3866529 , 17.6377233 ,  0.80264289,  0.54971847])

In [17]:
intercept=lr.intercept_

In [18]:
intercept

55.24069362844319

In [19]:
from sklearn.metrics import r2_score

In [20]:
r2=r2_score(y_test,y_pred)

In [21]:
r2

0.9887144552384186

In [25]:
class BGDRegressor:
    def __init__ (self,learning_rate=0.01,epochs=100):
        self.coef_=None
        self.intercept_=None
        self.lr=learning_rate
        self.epoch=epochs
        
    def fit(self,X_train,y_train):
        self.coef_=np.ones(X_train.shape[1])
        self.intercept_=0
        for i in range(self.epoch):
            y_pred=  X_train @ self.coef_ + self.intercept_  #X_train=(n,m),coef_=(m,1)
            slope_intercept=-2*(np.mean(y_train - y_pred))
            slope_coef = -2*((y_train-y_pred)@ X_train)/X_train.shape[0]
            
            self.intercept_ = self.intercept_ - (self.lr * slope_intercept)
            self.coef_ = self.coef_ - (self.lr * slope_coef)
        print(self.intercept_,self.coef_)
        
    def predict(self,X_test):
        return X_test @ self.coef_ + self.intercept_

In [26]:
bgd=BGDRegressor(learning_rate=0.08,epochs=60)

In [29]:
start=time.time()
bgd.fit(X_train,y_train)
print(f'Time taken is: {time.time()-start}')

55.23910020899935 0     7.386326
1    17.637285
2     0.802782
3     0.550044
dtype: float64
Time taken is: 0.10525894165039062

In [118]:
coef1=bgd.coef_

In [119]:
intercept1=bgd.intercept_

In [120]:
y_pred1=bgd.predict(X_test)

In [123]:
y_pred1

6252    55.006108
4684    22.314003
1731    47.592626
4742    30.975113
4521    43.313233
          ...
6412    47.183256
8285    62.988686
7853    16.481102
1095    63.640839
6929    46.236694
Length: 2000, dtype: float64

In [121]:
r21=r2_score(y_test,y_pred1)

In [122]:
r21

0.9887149110190311