In [56]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

In [2]:
df=pd.read_csv('../../Simple linear regression/tvmarketing.csv')

In [3]:
df.sample(5)

        TV  Sales
15   195.4   22.4
36   266.9   25.4
52   216.4   22.6
153  171.3   19.0
163  163.5   18.0

In [63]:
trf=ColumnTransformer([('trf_TV',StandardScaler(),['TV','Sales'])])

In [66]:
df1=trf.fit_transform(df)

In [68]:
df1=pd.DataFrame(df1)

In [69]:
df1

            0         1
0    0.969852  1.552053
1   -1.197376 -0.696046
2   -1.516155 -0.907406
3    0.052050  0.860330
4    0.394182 -0.215683
..        ...       ...
195 -1.270941 -1.234053
196 -0.617035 -0.830548
197  0.349810 -0.234898
198  1.594565  2.205347
199  0.993206 -0.119610

[200 rows x 2 columns]

In [70]:
X=df1.iloc[:,0].values
y=df1.iloc[:,-1]

In [71]:
X=X.reshape(-1,1)

In [72]:
X.shape

(200, 1)

In [73]:
X_train,X_test, y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [74]:
X_train.shape

(160, 1)

In [75]:
lr=LinearRegression()

In [76]:
lr.fit(X_train,y_train)

LinearRegression()

In [77]:
b=lr.intercept_

In [78]:
m=lr.coef_

In [82]:
print(b,m)

-0.011723395805823418 [0.76565558]

In [85]:
y_pred=lr.predict(X_test)

In [84]:
from sklearn.metrics import r2_score

In [86]:
r2_score(y_test,y_pred)

0.6766954295627077

In [87]:
class BGDRegressor:

    def __init__(self,learning_rate=0.001,epoch=100):
        self.m=1
        self.b=0
        self.lr=learning_rate
        self.epoch=epoch

    def fit(self,X_train,y_train):
        X_train=X_train.ravel()
        for i in range(self.epoch):
            slope_b= -2*np.sum(y_train - self.m*X_train - self.b)
            slope_m= -2*np.sum((y_train - self.m*X_train - self.b)*X_train)
            self.b= self.b- (self.lr*slope_b)
            self.m= self.m- (self.lr*slope_m)

        print(self.b,self.m)

    def predict(self,X_test):
        return self.m * X_test + self.b

In [88]:
gd=BGDRegressor()

In [90]:
gd.fit(X_train,y_train)

-0.011723395805823418 0.7656555838856122

In [92]:
gd_pred=gd.predict(X_test)

In [93]:
r2_score(y_test,gd_pred)

0.6766954295627077